import Head from 'next/head';

import { Courses } from './courses';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto py-10 w-full h-full'>
        <Courses />
      </main>
    </div>
  );
}
